### ISSUE TITLE
Fixed the styling and minor issues

### ISSUE THREAD

**Issue by Abinbn** [fliespl/broken-html-gamification#2]
# Let's see 👋
### Issues in the Primary Code:
1. Incorrect Syntax: The attempt to apply CSS styling within the `alert()` message using curly braces `{}` caused the text to display as code instead of being styled.
2. Incorrect Usage of `%c`: The `%c` placeholder is meant for styling console messages, not for styling text within an `alert()` dialogue box directly.

### Additions:
1. Implemented Custom Modal Dialog Box: Created a custom modal dialog box using HTML, CSS, and JavaScript to display the styled message.
2. Styled Text with HTML Markup: Applied red color styling to specific portions of the message using HTML markup `<span style="color: red;">` within the modal content.
3. JavaScript Functions: Added JavaScript functions to control the modal, including opening and closing it when required.
4. Modal Close Functionality: Enabled the modal to close when clicking on the close button (`&times;`) or outside of the modal content area.

### Here is the corrected code

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gamification - Level up your Experience</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="icon" href="favicon.ico">
    <style>
        
    </style>
</head>
<body>

<header>
    <h1>Gamification - Level up your Experience</h1>
    <nav>
        <ul>
            <li><a href="#about">About</a></li>
            <li><a href="#benefits">Benefits</a></li>
            <li><a href="#examples">Examples</a></li>
            <li><a target="_blank" href="https://oskarwegner.pl">About us</a></li>
        </ul>
    </nav>
</header>

<button onclick="openModal()">?</button>

<section id="about">
    <h2 style="text-align:center;">About Gamification</h2>
    <p>Gamification is the application of game-design elements and principles in non-game contexts. It involves using game mechanics, such as points, badges, and leaderboards, to engage users and motivate them to achieve specific goals. Gamification has gained popularity in various fields, including education, marketing, and employee training.</p>
    <p>Gamification taps into the natural human desire for competition, achievement, and rewards. By incorporating game elements into tasks or processes, it can enhance user engagement, promote learning, and drive desired behaviors.</p>
</section>

<section id="benefits">
    <h2 style="text-align:center;">Benefits of Gamification</h2>
    <div class="container">
        <div class="item">
            <h2>Increased Motivation</h2>
            <p>By incorporating game-like elements, such as challenges and rewards, gamification boosts motivation and encourages active participation.</p>
        </div>
        <div class="item">
            <h2>Enhanced Learning</h2>
            <p>Gamification makes learning fun and engaging, leading to improved knowledge retention and a deeper understanding of concepts.</p>
        </div>
        <div class="item">
            <h2>Improved Collaboration</h2>
            <p>Through team-based challenges and cooperative gameplay, gamification fosters collaboration and communication skills.</p>
        </div>
    </div>
</section>

<section id="examples">
    <h2 style="text-align:center;">Examples of Gamification</h2>
    <div class="container">
        <div class="item">
            <img src="https://via.placeholder.com/300" alt="Duolingo">
            <h2>Duolingo</h2>
            <p>A language learning platform that uses game-like features to make learning fun and addictive.</p>
        </div>
        <div class="item">
            <img src="https://via.placeholder.com/300" alt="Fitness Apps">
            <h2>Fitness Apps</h2>
            <p>Many fitness apps incorporate gamification to encourage users to stay active and reach their fitness goals.</p>
        </div>
        <div class="item">
            <img src="https://via.placeholder.com/300" alt="Starbucks Rewards">
            <h2>Starbucks Rewards</h2>
            <p>The Starbucks mobile app rewards customers with stars for purchases, unlocking special offers and free drinks.</p>
        </div>
        <div class="item">
            <img src="https://via.placeholder.com/300" alt="Badgeville">
            <h2>Badgeville</h2>
            <p>A gamification platform that helps businesses drive customer and employee engagement through rewards and achievements.</p>
        </div>
    </div>
</section>

<section id="newsletter">
    <h2>Subscribe to Our Newsletter</h2>
    <form id="newsletterForm">
        <input type="email" id="emailInput" placeholder="Enter your email" required>
        <button type="submit" id="subscribeBtn">Subscribe</button>
    </form>
    <p id="newsletterMsg"></p>
</section>




<!-- The Modal -->
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close" onclick="closeModal()">&times;</span>
    <p>The idea by <a href="https://github.com/fliespl" target="_blank">Fliespl</a>  but developed by <a href="https://github.com/Abinbn" target="_blank">Abinbn</a> </p>
  </div>
</div>


<footer>
    <p>&copy; 2024 Gamification World. All rights reserved.</p>
</footer>

<noscript>
    <script>
        alert('I am really sorry, but your browser doesn\'t support JavaScript!');
		alert('The idea by https://github.com/fliespl but developed by https://www.github.com/Abinbn');
    </script>
</noscript>

<!-- Edited and beautified by https://www.github.com/Abinbn -->
</body>
</html>

``` 

```css
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            color: #333;
            margin: 0;
            padding: 0;
            scroll-behavior: smooth; 
        }
        header {
            background-color: #4CAF50; 
            color: white;
            padding: 20px;
            text-align: center;
            position: static;
            max-width: 100vw;
            top: 0px;
        }
        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }
        nav ul li {
            display: inline;
            margin-right: 20px;
        }
        nav ul li a {
            color: white;
            text-decoration: none;
        }
        section {
            padding: 20px;
            margin-top: 100px;
        }
        .container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-evenly;
        }
        .item {
            width: 30%;
            background-color: #f8f9fa;
            margin-bottom: 20px;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .item img {
            width: 100%;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .item h2 {
            color: #4CAF50;
        }
        footer {
            background-color: #4CAF50;
            color: white;
            text-align: center;
            padding: 10px;
            position: static;
            bottom: 0;
            max-width: 100vw;
        }
        button {
            padding: 10px 20px;
            margin: 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            background-color: #4CAF50;
            color: white;
        }
        button:hover {
            background-color: #45a049; 
        }
        
        button:active {
            transform: scale(0.95);
        }
        
        html {
            scroll-behavior: smooth;
        }



#newsletter {
    text-align: center;
    margin-top: 50px;
}

#newsletter h2 {
    color: #4CAF50;
    font-size: 24px;
}

#newsletterForm {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 20px;
}

#emailInput {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    width: 300px;
    margin-right: 10px;
}

#subscribeBtn {
    padding: 10px 20px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

#subscribeBtn:hover {
    background-color: #45a049;
}

#newsletterMsg {
    margin-top: 10px;
    color: #4CAF50;
}





.modal {
  display: none;
  position: fixed;
  z-index: 1;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  /* background-color: rgb(0,0,0); */
  background-color: rgba(0,0,0,0.4);
  
}

.modal-content {
  background-color: #fefefe;
  margin: 15% auto;
  padding: 20px;
  border: 1px solid #888;
  width: 50%;
  height: 50px;
  border-radius:10px ;
  /* box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); */

}

.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}
``` 

```javascript
document.addEventListener("DOMContentLoaded", function() {
    const newsletterForm = document.getElementById("newsletterForm");
    const emailInput = document.getElementById("emailInput");
    const newsletterMsg = document.getElementById("newsletterMsg");

    newsletterForm.addEventListener("submit", function(event) {
        event.preventDefault();
        const email = emailInput.value;
        if (isValidEmail(email)) {
            setTimeout(function() {
                newsletterMsg.textContent = "Thank you for subscribing!";
                newsletterMsg.style.color = "#4CAF50";
                emailInput.value = "";
            }, 1000);
        } else {
            newsletterMsg.textContent = "Please enter a valid email address.";
            newsletterMsg.style.color = "red";
        }
    });

    function isValidEmail(email) {
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        return emailRegex.test(email);
    }
});

// alert('The idea by github.com/fliespl but developed by %c[github.com/Abinbn]', 'color: red;');




function openModal() {
  document.getElementById('myModal').style.display = "block";
}

function closeModal() {
  document.getElementById('myModal').style.display = "none";
}

window.onclick = function(event) {
  var modal = document.getElementById('myModal');
  if (event.target == modal) {
    modal.style.display = "none";
  }
}

``` 

`By Abinbn from India ☕`
